server:
  port: 8001


spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.zaxxer.hikari.util.DriverDataSource  #当前数据库操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db2019?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root


mybatis:
  mapper-locations: classpath*:mapper/*.xml    #mybatis管理文件
  type-aliases-package: com.atguigu.springcloud.entities  #实体类的位置

