server:
  port: 3344

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone:  http://eureka7001.com:7001/eureka/,http://eureka7002.7002/eureka/ #集群版
  instance:
    instance-id: config3344
    prefer-ip-address: true

spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/a492421512/cloud-config.git #github仓库上面的git仓库名字
          default-label: master
          search-paths: /** #搜索目录
          #basedir: target/config
            #读取分支
      label: master